# Generated by Django 5.1.6 on 2025-02-12 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Registration',
                'verbose_name_plural': 'User Registrations',
            },
        ),
    ]
